[package]
name = "quack-bm"
version = "0.1.0"
edition = "2021"

[dependencies]
quack = { path = "../quack", features = ["libpari", "power_table"] }
clap = { version = "4.0.26", features = ["derive"] }
rand = "0.8.5"
log = "0.4.17"
env_logger = "0.9.3"
multiset = "0.0.5"
sha2 = "0.10.6"
